### PR TITLE
add deprecated column

### PR DESCRIPTION
**Pull request by richardlehane**
Some of the PUIDs in the list needing signatures are deprecated (mostly those without extension or byte sigs). I've added a deprecated column and populated for the ones I could find.

### CODE REVIEW

**Comment by Dclipsham** [comment]
v grateful, Thank you Richard

**Comment by DavidUnderdown** [comment]
I can easily generate a list of formats from the database with deprecated in the description (just as I did for outline records).

I notice though, looking at the table structure, that there's actually two fields relating to the withdrawal of a format.  Not clear just from looking at it whether this was intended to record an specific action by the developer of the format, or if this was supposed to be for what we've since called deprecation of a format record by us.  The withdrawn flag is set in two instances, while the withdrawn date for just one.  The two are Broadcast WAVE fmt/1 (which also has withdrawn date) and JTIP fmt/149.

**Comment by Dclipsham** [comment]
fmt/1 isn't deprecated and still has a signature. I've always understood the 'withdrawn' flag to mean withdrawn by the format vendor. the JTIP description seems to support that notion. When I've deprecated I've added a deprecation statement to the description field, and removed all internal and external identifiers (obvs excluding PUID). A few years back I removed all identifiers from all deprecated formats I could find, but it would be useful to see if any descriptions contain the word, but still retain any identifier (including MIME)

**Comment by Dclipsham** [comment]
separately I wonder if the 'withdrawn' flag on fmt/1 is the result of an errant click on data entry. We can include more explicit flags for deprecation in the pronom-next requirements

**Pull request merged**
